### ISSUE TITLE
Charge Point not showing up in Operations (steve knows CP, shows heartbeat and other data)

### ISSUE THREAD

**Issue by jb-y** [steve-community/steve#1114]
- I added Charge Point in steve (steve also picked up Charge Point under Uknown Charge Points as I turned the flag to true in main.properties)
- Charge Point station has steve's server url which is public (running on AWS LightSail)
- Steve knows the charge point as it shows model, ocpp version (1.5S) and other details
- Charge Point does not show up in operations

In summary, Steve knows the charge point station, gets all the details (ex. model, ocpp version) but doesn't show up in operations. I've attached screenshots for your reference. I am not sure what could be the issue. I can also attach logs from Steve.

<img width="1469" alt="steve-1" src="https://user-images.githubusercontent.com/128639650/230560079-0bdb9741-fa6b-4bbe-b2fc-c6498c340a04.png">
<img width="1449" alt="steve-2" src="https://user-images.githubusercontent.com/128639650/230560095-c92fa1af-a08d-426e-a325-90078ffc21c3.png">
<img width="1408" alt="steve-3" src="https://user-images.githubusercontent.com/128639650/230560131-4dd67a69-60e0-45b5-b030-7bbf2e875593.png">

**Comment by goekay** [comment]
hey @jb-y since this is a charge point using soap, steve has to know the endpoint address to send messages to. as you see from your last screenshot, this is not set. therefore, steve cannot contact this station and we filter it out.

the endpoint address is set by charging station. it is one of the soap headers. apparently this is not arriving at steve.

**Comment by jb-y** [comment]
thanks, that's helpful!
