### ISSUE TITLE
Possible Inconsistency in Transaction Handling with Blocked `idTag`

### ISSUE THREAD

**Issue by Tano-Coppoletta** [steve-community/steve#1286]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.6.0
Operating system  : Ubuntu 22.04.1
JDK               : openjdk version "11.0.20.1"
Database          : version 1.0.3
```

#### Expected Behavior

The system should reject the initiation of a transaction when a `StartTransaction` message contains a blocked `idTag`, as per the OCPP protocol specifications. No `transactionId` should be generated, and no new entry should be created in the transactions database.

#### Actual Behavior

The system generates a `transactionId` and creates a new entry in the transactions database despite the `idTag` being blocked. This behavior is inconsistent with the OCPP protocol specifications, which state that a blocked `idTag` should not be allowed for charging.

#### Steps to Reproduce the Problem

  1. Send a `StartTransaction` message with a blocked `idTag`.
  2. Observe that the system’s response includes a `transactionId`, indicating that the transaction has been initiated.
  3. Check the transactions database and note that a new transaction entry has been created, despite the `idTag` being blocked.

#### Additional context

This inconsistency in behavior could potentially lead to unauthorized use of the charging services if exploited maliciously. It could possibly allow for actions contrary to intended permissions and restrictions.

**Comment by goekay** [comment]
you are only thinking about real-time communication cases, where charge stations are online all the time and have a stable constant connection to steve. i think steve was working like this initially.

however, there are situations where stations lose internet connectivity and become offline. they might operate without talking to steve. they might allow to start and stop transactions based on idTag cache (or whitelists). therefore, they would keep track of these transactions and let steve know later. therefore, there are cases where transactions are coming from the past. steve has to allow and store them in database. otherwise, we would lose valuable historical transactional information.

steve still responds with the correct status of the idTag though. a proper charging station implementation should respect this status and immediately stop the transaction in real-time cases.
