### ISSUE TITLE
Logs are Unavailable

### ISSUE THREAD

**Issue by lmccarty5** [steve-community/steve#1503]
SteVe Version     : 3.6.0
Operating system  : Ubuntu 22.04 Virtual Machine Running on Windows 11 Host
JDK               :  java 21.0.2  on host

#### Expected Behavior

when hitting the log button on the steve web interface, a log will appear

#### Actual Behavior

a mostly blank page appears that says steve log unavailable
<img width="826" alt="not available" src="https://github.com/steve-community/steve/assets/31521378/9a5a2729-b998-49b2-8141-ec87365a9bc7">

#### Steps to Reproduce the Problem

  1. open steve directory
  2. start docker 
  3. open web interface
  4. hit logs button in top right
  5. get logs unavailable error

**Comment by juherr** [comment]
When running Steve with Docker, there is currently no log available in the web interface. 

This is in line with the expected behavior when running "cloud" services, as outlined in the 12-factor methodology for building software-as-a-service applications. 
To address this, it is recommended to redirect the image output into a dedicated log service. 

Furthermore, it may be advisable to hide the log link when it is not available.

**Comment by lmccarty5** [comment]
Do you have any documentation or resources that could help me with redirecting the image output to a dedicated log service?

**Comment by juherr** [comment]
You'll find many articles.

One of them https://sharmarajdaksh.github.io/blog/shoving-your-docker-logs-to-elk
