### ISSUE TITLE
connector_id - which error code gets shown

### ISSUE THREAD

**Issue by rdc-Green** [steve-community/steve#937]
i've noted that some connector status rows use connector_id 0 whereas others use connector_id 1 (assuming charge points only have 1 socket).

It looks as though steve is set up to show 'Faulted' errors no matter which connector_id this is on. Is this the case and are you able to show how this is done / if this information is available in a table/view in the db

Thank you

**Comment by goekay** [comment]
0 is a special connector id, and represents status information of the whole station. in cases it can be used to override the status information of specific connectors. steve is configured in a way that, if there is a more recent connector status for 0, only this 0 is shown. the others are not rendered since they would be older. see #16 

there is no specific logic/filtering for 'Faulted' errors.

**Comment by rdc-Green** [comment]
Thank you
